# Generated by Django 4.0.6 on 2022-09-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('tipo_cartao', models.CharField(choices=[('S', 'Cartão Padrão'), ('G', 'Cartão Gold'), ('P', 'Cartão Platinum'), ('B', 'Cartão Black')], default='S', max_length=1)),
                ('numero', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('bandeira', models.CharField(max_length=10)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cvc', models.CharField(max_length=3)),
                ('validade', models.DateField()),
                ('dia_vencimento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=30)),
                ('nasc', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Genero masculino'), ('F', 'Genero feminino'), ('O', 'Genero outro'), ('N', 'Genero não especificado')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('P', 'Conta Poupança'), ('C', 'Conta Corrente'), ('S', 'Conta Salário')], default='C', max_length=1)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fisrt_parcela', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_parcelas', models.IntegerField()),
                ('juros', models.DecimalField(decimal_places=2, max_digits=3)),
                ('situacao', models.BooleanField()),
                ('aprovado', models.BooleanField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='loja/imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=30)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta_reciver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta_reciver', to='home.conta')),
                ('conta_sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conta_sender', to='home.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Pgmt_emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pag', models.DateField()),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.contatos')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cartoes')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.conta')),
                ('transacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.transacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=15)),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(max_length=10)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cartoes',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.conta'),
        ),
    ]
